elastic/kibana-load-testing

- .ci/Jenkinsfile
Blocked by [#infra/25204](https://github.com/elastic/infra/pull/25204)
To run load testing on a specific stack version this PR adds reading from build parameters
> [Kibana CI] Set stack version in build parameters

- .ci/Jenkinsfile
Support "7.x" stack version as parameter, the value is hardcoded and should be updated with new minor release in place
> [ci] support 7.x stack version

- src/test/resources/test/lastDeployment.txt
- src/test/scala/org/kibanaLoadTest/helpers/Helper.scala
- src/test/scala/org/kibanaLoadTest/scenario/Canvas.scala
- src/test/scala/org/kibanaLoadTest/scenario/Dashboard.scala
- src/test/scala/org/kibanaLoadTest/scenario/Discover.scala
- src/test/scala/org/kibanaLoadTest/simulation/DemoJourney.scala
- src/test/scala/org/kibanaLoadTest/test/HelpersTest.scala
Allow `readFileToMap` to handle empty string values, small cleanup
> fix readFileToMap

- src/test/scala/org/kibanaLoadTest/helpers/CloudHttpClient.scala
- src/test/scala/org/kibanaLoadTest/simulation/BaseSimulation.scala
- src/test/scala/org/kibanaLoadTest/test/CloudAPITest.scala
- src/test/scala/org/kibanaLoadTest/test/HelpersTest.scala
Fix issue spotted by [jenkins](https://kibana-ci.elastic.co/job/elastic+kibana+load-testing/153/) run:
- timeout is ignored and job won't stop if deployment is unhealthy
- failed deployment is not deleted and remains after test run
> fix timeout check in waitForClusterToStart

- .ci/Jenkinsfile
- README.md
- src/test/scala/org/kibanaLoadTest/simulation/BaseSimulation.scala
This PR allows to set custom deployment conf file with system variable: `-DeploymentConf=file/in/resources`:
```
14:07:12  Running tests against Kibana cloud instance
14:07:12  + cd kibana-load-testing
14:07:12  + mvn clean -q -Dmaven.test.failure.ignore=true compile
14:07:12  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
14:07:27  + mvn gatling:test -q -DcloudStackVersion=8.0.0-SNAPSHOT -DdeploymentConfig=config/deploy/default.conf -Dgatling.simulationClass=org.kibanaLoadTest.simulation.DemoJourney
```
> [cloud] Support custom deployment config

- .ci/Jenkinsfile
- src/test/scala/org/kibanaLoadTest/simulation/DemoJourney.scala
Turns out we can use a less power worker to run load testing on cloud or build kibana run tests against it on the same worker.
There is no significant time change, building kibana and running tests still takes around ~40 min; testing on cloud is ~ 11 min
> Change worker

- .ci/Jenkinsfile
- src/test/scala/org/kibanaLoadTest/KibanaConfiguration.scala
- src/test/scala/org/kibanaLoadTest/simulation/BaseSimulation.scala
- src/test/scala/org/kibanaLoadTest/simulation/local/AllAtOnceJourney.scala
atOnce 120:
```
Global Information --------------------------------------------------------
> request count                                       2280 (OK=2280   KO=0     )
> min response time                                     18 (OK=18     KO=-     )
> max response time                                  17050 (OK=17050  KO=-     )
> mean response time                                  3296 (OK=3296   KO=-     )
> std deviation                                       3721 (OK=3721   KO=-     )
> response time 50th percentile                       1824 (OK=1824   KO=-     )
> response time 75th percentile                       5188 (OK=5188   KO=-     )
> response time 95th percentile                      13703 (OK=13703  KO=-     )
> response time 99th percentile                      16390 …
```
> Add simulation for locally build Kibana

- src/test/scala/org/kibanaLoadTest/helpers/Helper.scala
- src/test/scala/org/kibanaLoadTest/ingest/Main.scala
- src/test/scala/org/kibanaLoadTest/test/HelpersTest.scala
Fixing ingestion that was probably broken by [multiple reports](https://github.com/elastic/kibana-load-testing/commit/de31fb3fc31de812861e5c42227643f0f19abbe2)
> Fix report ingestion

- src/test/scala/org/kibanaLoadTest/helpers/ESWrapper.scala
- src/test/scala/org/kibanaLoadTest/helpers/Helper.scala
- src/test/scala/org/kibanaLoadTest/helpers/SimulationHelper.scala
- src/test/scala/org/kibanaLoadTest/ingest/Main.scala
- src/test/scala/org/kibanaLoadTest/simulation/BaseSimulation.scala
- src/test/scala/org/kibanaLoadTest/test/IngestionTest.scala
ingest deploymentId, CI_BUILD_ID, CI_RUN_URL in order to filter/search data
```
"_source": {
"timestamp": "2021-02-02T15:47:14.419Z",
"name": "query gauge data",
"requestSendStartTime": "2021-02-02T15:45:49.172Z",
"responseReceiveEndTime": "2021-02-02T15:46:01.188Z",
"status": "OK",
"requestTime": 12016,
"message": "",
"version": "8.0.0",
"buildHash": "fb19aab307fb80740b60fbd4a0861e75380e96f9",
"buildNumber": 40008,
"branch": "",
"isSnapshotBuild": true,
"baseUrl": "https://f4c2dd26df52441a8e9804d861dae720.us-central1.gcp.foundit.no:9243",
"scenario": "org.kibanaLoadTest.simulation.cloud.AtOnceJourney",
"maxUsers": 80,
"deploymentId": "4fc29576b274488788eab2b3f8e61776",
"isCloudDeployment": true,
"CI_BUILD_ID": "261",
"CI_BUILD_URL": …
```
> ingest more data to build stats

- .ci/Jenkinsfile
- .ci/Jenkinsfile_cloud
Since we need to run regularly both on cloud and from source, it makes sense to have 2 separate jobs with its own Jenkinsfile
> [ci] split logic cloud vs source

- .ci/Jenkinsfile_cloud
- .ci/loadPipeline.groovy
- src/test/scala/org/kibanaLoadTest/helpers/CloudHttpClient.scala
- src/test/scala/org/kibanaLoadTest/helpers/Helper.scala
- src/test/scala/org/kibanaLoadTest/helpers/SimulationHelper.scala
- src/test/scala/org/kibanaLoadTest/simulation/BaseSimulation.scala
This PR is adding docker image with maven 3.6.3 in order to unblock #67
I also made changes to pipeline so that it run faster by default (1 test thread), but it no longer allows to spin up multiple pipelines at once. It won't be required that much as soon as it will be possible to run multiple simulations against a single deployment
> [ci] Run cloud testing in docker container

- src/test/resources/cloudPayload/searchDeployments.json
- src/test/scala/org/kibanaLoadTest/deploy/DeleteAll.scala
- src/test/scala/org/kibanaLoadTest/helpers/CloudEnv.scala
- src/test/scala/org/kibanaLoadTest/helpers/CloudHttpClient.scala
- src/test/scala/org/kibanaLoadTest/test/CloudAPITest.scala
PR is adding class to stop running deployments:
`export API_KEY=<your_cloud_key>`
`mvn exec:java -Dexec.mainClass=org.kibanaLoadTest.deploy.DeleteAll -Dexec.classpathScope=test -Dscope=all` will stop all running deployments:
```
21:48:44.724 [INFO ] httpClient - Search for running deployments
21:48:45.957 [INFO ] deploy:DeleteAll - Found 1 running deployments
21:48:45.957 [INFO ] deploy:DeleteAll - Deleting all deployments
21:48:45.958 [INFO ] deploy:DeleteAll - Got 1 deployments to delete
21:48:45.958 [INFO ] httpClient - deleteDeployment: Deployment bdcfa757001e41e883b60f373e43500c
21:48:47.308 [INFO ] httpClient - deleteDeployment: Finished with status code 200
21:49:09.311 [INFO ] httpClient - Search for running deployments
21:49:10.062 [INFO ] deploy:DeleteAll - Found 0 deployments …
```
> adding class to stop deployments

- .ci/Jenkinsfile
Jobs are failing with `GCS_UPLOAD_PREFIX environment variable is not set and must always be set on CI`
This PR is about to fix it
> [CI] fix kibana load-testing pipeline

- .ci/Jenkinsfile_cloud
In order to create specific deployment on cloud it may require a extra permissions, for that purpose it is possible to override vault key with yours very own.
> [ci] add DEPLOY_SECRET param

- .ci/Jenkinsfile_cloud
- scripts/deploy_and_test.sh
- src/test/scala/org/kibanaLoadTest/deploy/Create.scala
- src/test/scala/org/kibanaLoadTest/helpers/CloudHttpClient.scala
- src/test/scala/org/kibanaLoadTest/helpers/SimulationHelper.scala
- src/test/scala/org/kibanaLoadTest/helpers/Version.scala
- src/test/scala/org/kibanaLoadTest/test/CloudAPITest.scala
Closes #92
With this PR you can pass multiple stack version in `STACK_VERSION` job parameter: for each version deployment is created, scenarios are run, deployment is deleted.
- you can provide sequence of existing versions, e.g. `7.11.1, 7.13.0-SNAPSHOT,8.0.0-SNAPSHOT`
- you can use `.x` to get the latest available version on Cloud, e.g `7.11.x,7.x`  
Deployments/scenarios are run in a sequence to avoid confusing with ingested test results. It means job time is going up by specifying multiple versions; it should be kept in mind.
Default value: `7.x,8.0.0-SNAPSHOT`, replace if you don't need to test 2 versions
Scheduled daily run uses the default value
> [ci] run the latest 7.x snapshot on Cloud

- src/test/resources/cloudPayload/createDeployment.json
- src/test/resources/config/deploy/apm-default.conf
- src/test/resources/config/deploy/apm-disable-instrumentation.conf
- src/test/resources/config/deploy/apm-no-async.conf
- src/test/resources/config/deploy/apm-no-metrics.conf
- src/test/resources/config/deploy/apm-no-span-stacktrace.conf
- src/test/resources/config/deploy/computeOptmized.conf
- src/test/resources/config/deploy/custom.conf
- src/test/resources/config/deploy/default.conf
- src/test/resources/config/deploy/memoryOptimized.conf
- src/test/scala/org/kibanaLoadTest/helpers/CloudHttpClient.scala
Part of #98 
With this PR you can can create a more flexible cloud deployment, e.g.
```
elasticsearch {
deployment_template = "gcp-io-optimized"
autoscaling_enabled = true
hot_content {
zone_count = 3
instance_configuration_id = "gcp.data.highio.1"
memory = 8192
}
}
kibana {
zone_count = 2
memory = 1024
}
apm {
memory = 512
}
```
For a new deployment ES `hot_content` cluster will be in 3 zone instead of 2 and auto-scaling is on, Kibana will be in 2 zones instead of 1 by default.
> Add configs for hardware profiles

- src/test/scala/org/kibanaLoadTest/simulation/branch/AtOnceJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/DemoJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/DiscoverAtOnce.scala
With this PR the following changes are made:
- AtOnceJourney 500 users
- DiscoverAtOnce 500 users
- DemoJourney ramping up to 800 (~954 totally)
> Branch testing: changing max users count

- .ci/Jenkinsfile
- puppeteer/src/helpers/compare.ts
- puppeteer/src/helpers/results.ts
- scripts/archive_results.sh
Currently the script fails without attaching artifacts, that shows the difference in requests sequence and baseline. This PR fixes it.
https://kibana-ci.elastic.co/view/Kibana/job/elastic+kibana+load-testing/577
> [ci] Save report on failure

- .ci/Jenkinsfile
This PR increases job timeout 90 -> 120 min. After adding 3 more simulations job time is around 80-95 min 
> [ci] increase timeout to 2h for branch testing

- src/test/scala/org/kibanaLoadTest/scenario/Dashboard.scala
PR fixes parsing of 
`/api/saved_objects/_find?default_search_operator=AND&has_reference=%5B%5D&page=1&per_page=1000&search_fields=title%5E3&search_fields=description&type=dashboard` by filtering response by dashboard name
> [dashboard] filter response by specific dashboard

- scripts/archive_results.sh
With response.log being part of report, artifacts archive for a single CI run is ~1GB. Since we ingest data from the log file, there is no need to keep it in report.
> [ci] exclude *.log files from artifacts

- src/test/scala/org/kibanaLoadTest/helpers/Helper.scala
- src/test/scala/org/kibanaLoadTest/simulation/BaseSimulation.scala
This PR fixes
```
08:28:17.539 [main][WARN ][ZincCompiler.scala:183] i.g.c.ZincCompiler$ - /Users/dzmitrylemechko/elastic/github/kibana-load-testing/src/test/scala/org/kibanaLoadTest/helpers/Helper.scala:182:11: class JSONObject in package json is deprecated (since 1.0.6): Use The Scala Library Index to find alternatives: https://index.scala-lang.org/
parse(JSONObject(meta).toString()).getOrElse(Json.Null)
^
08:28:19.367 [main][WARN ][ZincCompiler.scala:144] i.g.c.ZincCompiler$ - one warning found
```
by switching to `Gson` library
> [chore] remove deprecated until json method

- src/test/resources/cloudPayload/createDeployment.json
- src/test/resources/cloudPayload/createExtendedDeployment.json
- src/test/resources/config/deploy/computeOptmized.conf
- src/test/resources/config/deploy/default.conf
- src/test/resources/config/deploy/memoryOptimized.conf
- src/test/scala/org/kibanaLoadTest/deploy/Create.scala
- src/test/scala/org/kibanaLoadTest/helpers/CloudHttpClient.scala
- src/test/scala/org/kibanaLoadTest/helpers/SimulationHelper.scala
- src/test/scala/org/kibanaLoadTest/test/CloudAPITest.scala
To speed up process and depend less on APM stability, default cluster will include only ES and Kibana.
To create deployment with APM it now requires to have it explicitly specified in `.conf` file:
```
apm {
memory = 1024
}
```
> [cloud] don't deploy APM by default

- src/test/scala/org/kibanaLoadTest/helpers/Helper.scala
Fixing ingestion failure:
```
08:38:13  org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=mapper [rootNode.content] cannot be changed from type [date] to [text]]
08:38:13      at org.elasticsearch.rest.BytesRestResponse.errorFromXContent (BytesRestResponse.java:176)
08:38:13      at org.elasticsearch.client.RestHighLevelClient.parseEntity (RestHighLevelClient.java:2011)
08:38:13      at org.elasticsearch.client.RestHighLevelClient.parseResponseException (RestHighLevelClient.java:1988)
08:38:13      at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest (RestHighLevelClient.java:1745)
08:38:13      at org.elasticsearch.client.RestHighLevelClient.performRequest (RestHighLevelClient.java:1702)
08:38:13      at …
```
> [ingestion] convert map to java collection for GSON

- src/test/scala/org/kibanaLoadTest/helpers/ESClient.scala
- src/test/scala/org/kibanaLoadTest/test/IngestionTest.scala
Improve ingestion speed with `BulkRequest`
Before:
```
15:24:47.672 [INFO ] ES_Client - Ingesting to stats cluster: 6136 docs
15:26:06.109 [INFO ] ES_Client - Ingestion is completed
// 1 min 19 sec
...
15:26:11.165 [INFO ] ES_Client - Ingesting to stats cluster: 2662 docs
15:26:46.768 [INFO ] ES_Client - Ingestion is completed
// 35 sec
```
After
```
15:35:21.947 [INFO ] ES_Client - Ingesting to stats cluster: 6136 docs
15:35:37.739 [INFO ] ES_Client - Ingestion is completed
// 16 sec
...
15:35:37.765 [INFO ] ES_Client - Ingesting to stats cluster: 281 docs
15:35:37.913 [INFO ] ES_Client - Ingestion is completed
// 0.15 sec
```
> [ingest] use BulkRequest with 200 docs per chunk to ingest results faster

- src/test/scala/org/kibanaLoadTest/helpers/ESClient.scala
Fixes Jenkins error in run [670](https://kibana-ci.elastic.co/view/Kibana/job/elastic+kibana+load-testing/670)
```
11:21:31  ElasticsearchStatusException[Unable to parse response body]; nested: ResponseException[method [POST], host [https://********], URI [/_bulk?timeout=1m], status line [HTTP/1.1 413 Request Entity Too Large]
11:21:31  ];
11:21:31  	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1991)
11:21:31  	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1745)
11:21:31  	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1702)
11:21:31  	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1672)
``` …
> [ingest] set default size to 100 for bulk request

- src/test/scala/org/kibanaLoadTest/simulation/cloud/AtOnceJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/cloud/DemoJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/cloud/DiscoverAtOnce.scala
Gatling stats shows significant improvement so it makes sense to increase the load
> [cloud] bump concurrent users up to 100/250

- src/test/scala/org/kibanaLoadTest/helpers/Helper.scala
Fixes pipeline failure for 7.x branch
> [helper] fix moveResponseLogToResultsDir to support 7.x

- puppeteer/src/helpers/compare.ts
- puppeteer/src/scenario/demoJourney.ts
- src/test/scala/org/kibanaLoadTest/helpers/ESClient.scala
- src/test/scala/org/kibanaLoadTest/helpers/Helper.scala
- src/test/scala/org/kibanaLoadTest/helpers/LogParser.scala
- src/test/scala/org/kibanaLoadTest/ingest/Main.scala
- src/test/scala/org/kibanaLoadTest/test/IngestionTest.scala
Since we run many simulations, it is important to run ingestion in a reasonable time. This PR changes json structures to use Array instead of List, while loop instead of forEach and add error handling when records some records are missing (we merge it from 2 files)
> [ingest] Optimize test results ingestion 

- src/test/scala/org/kibanaLoadTest/helpers/ResponseParser.scala
With this PR we will ingest actual response headers and body only when request status is `KO`, meaning Gatling identified it as failure. By default both fields will have empty string.
> [ingest] do not ingest response headers and body

- puppeteer/src/scenario/demoJourney.ts
- scripts/build_and_test.sh
To make results more consistent and do not depend on Kibana/ES state after previous simulation, this PR re-starts Kibana/ES for each simulation
> [branch] restart kibana & ES for each simulation

- src/test/resources/test/global_stats.json
- src/test/resources/test/testRun.txt
- src/test/scala/org/kibanaLoadTest/helpers/Helper.scala
- src/test/scala/org/kibanaLoadTest/helpers/LogParser.scala
- src/test/scala/org/kibanaLoadTest/test/IngestionTest.scala
This PR adds 2 fields to gatling-stats index and for each simulation we gonna have few more metrics:
- `totalUsersCount` showing how many virtual users totally went through journey  
- `avgUserSessionTIme` showing avg time of user journey, basically how much time its takes to run all the requests on average
> ingest total user count and avg user session time

- src/test/scala/org/kibanaLoadTest/helpers/LogParser.scala
simulation.log generated by gatling has often less records stating user session end than the start session ones.
This PR changes the logic to collect start/end lines in 2 array and cut the first one to have the equal number of elements with the other one. We lost some data, but results mostly should be representative.  
> Fix avg user session time calculation

- cfg/metricbeat/metricbeat.yml
This should fix the long list of clusters in the monitoring window.
New  has the same length as the ones already set so it should work just fine. I guess we have to run the test a few time after merging to confirm that this is right.
> Add override to cluster uuid

- cfg/metricbeat/metricbeat.yml
Found a pipeline setting for metricbeat output, hopefully it also works for cloud.id and for monitoring data. 
https://www.elastic.co/guide/en/beats/metricbeat/7.16/configuring-ingest-node.html
I've already created the pipeline in Kibana Stats that sets the cluster uuid to : "dima-s-awesome-cluster"
> Adding a pipeline to set the cluster UUID

- .ci/Jenkinsfile
Speeds up kibana repo clone process by lmiting number of commits to 20, no tags, etc.
> checkout faster

- src/test/scala/org/kibanaLoadTest/helpers/ESClient.scala
- src/test/scala/org/kibanaLoadTest/helpers/Response.scala
- src/test/scala/org/kibanaLoadTest/helpers/ResponseParser.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/CanvasJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/DashboardJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/DemoJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/DiscoverJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/LensJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/TSVBGaugeJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/TSVBTimeSeriesJourney.scala
PR splits each simulation into 2 scenarios: warmup and main one
- warmup includes
- 1st stage of 20 concurrent users during 30 sec
- 2nd stage of ramping concurrent users from 20 to <max> during 2 minutes
- main includes
- <max> concurrent users during 4 minutes
> Add warmup stage for simulations

- pom.xml
- src/test/scala/org/kibanaLoadTest/helpers/ESClient.scala
Add some code to print the failures.
Ingestion is broken to the `gatling-data` data stream.
Fixing it here.
> [Ingestion] Fix Ingestion

- scripts/build_and_test.sh
Fix load testing execution on Jenkins by running FTR from root.
> [ci] Run FTR from kibana rootDir

- src/test/scala/org/kibanaLoadTest/helpers/ESClient.scala
This PR removes logging every bulk beeing ingested, instead I added a sum up time execution for each index:
```
12:14:24  12:14:24.215 [org.kibanaLoadTest.ingest.Main.main()] INFO ES_Client - Ingesting to 'gatling-********' index: 1 docs
12:14:25  12:14:24.925 [org.kibanaLoadTest.ingest.Main.main()] INFO ES_Client - Ingestion is completed. Took: 0 minutes 0 seconds
12:14:25  12:14:24.925 [org.kibanaLoadTest.ingest.Main.main()] INFO ES_Client - Ingesting to 'gatling-data' index: 49630 docs
12:15:31  12:15:31.020 [org.kibanaLoadTest.ingest.Main.main()] INFO ES_Client - Ingestion is completed. Took: 1 minutes 6 seconds
12:15:31  12:15:31.021 [org.kibanaLoadTest.ingest.Main.main()] INFO ES_Client - Ingesting to 'gatling-users' index: 4346 docs
12:15:33  12:15:32.746 …
```
> [Ingestion] Remove extended logging

- src/test/resources/logback.xml
- src/test/scala/org/kibanaLoadTest/helpers/Helper.scala
- src/test/scala/org/kibanaLoadTest/ingest/Main.scala
- src/test/scala/org/kibanaLoadTest/simulation/BaseSimulation.scala
- src/test/scala/org/kibanaLoadTest/test/DataStreamIngestionTest.scala
- src/test/scala/org/kibanaLoadTest/test/IngestionTest.scala
Closes #281
Unfortunately, it looks like we can't customise [StatsProcessor](https://github.com/gatling/gatling/blob/860a4b0ff9bca16c39ab4eb2ca13e567c70f35df/gatling-http/src/main/scala/io/gatling/http/engine/response/StatsProcessor.scala#L58-L76) in Gatling to log less information about call response.
Taking this into account, I disabled response logging and from now on each document will represent only request data, but not response: we were collecting request body, request headers and response code before. We can still use Gatling status (OK/KO) to identify failed requests. Valid http method / path for GenericJourney will be stored in `name` field, I will update the existing scenarios to follow the pattern.
> [Ingestion/Results reporting] Disable response logging

- pom.xml
This PR updates Gatling version to the latest one: 3.8.3
Should be testing on CI, as soon as we update maven version to 3.8.6 on a worker.
> update Gatling to 3.8

- src/test/scala/org/kibanaLoadTest/simulation/generic/GenericJourney.scala
While running scalability test with `promotion_tracking_dashboard-0182cff0-e8d8-42f1-b3c5-1f2e71dc7862.json` I faced the parsing error:
```
Caused by: io.gatling.core.session.el.ElParserException: Failed to parse {"timerange":{"timezone":"Europe/Berlin" ...
{},"searchSession":{"sessionId":"fe0c8502-ded9-43d0-b2ca-a6daa22a6717","isRestore":false,"isStored":false}}
```
It happens when request body in json contains a string like `#{arg0}` or `${arg0}` and Gatling interprets it as action search for `arg0` attribute in session object and pass it instead.
So the code `.body(StringBody(bodyString))` was failing since there are no attributes with searched name in the session.
The fix is to replace #|$ with ##|$$ and suggested by Gatling team.
> Escape #|$ so gatling don't apply session values

- README.md
- src/test/scala/org/kibanaLoadTest/KibanaConfiguration.scala
- src/test/scala/org/kibanaLoadTest/simulation/generic/GenericJourney.scala
It will be easier to use env var to override hosts and etc, at least on CI
> Override GenericJourney config via env var

- src/test/scala/org/kibanaLoadTest/simulation/generic/GenericJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/generic/mapping/Http.scala
Follow-up to elastic/kibana#140092
This PR updates GenericJourney to use url query for API requests built on APM data.
> GenericJourney: support url query

- src/test/scala/org/kibanaLoadTest/simulation/generic/GenericJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/generic/mapping/Step.scala
elastic/kibana/pull/140680 changed scalabilitySetup structure (introduced `userCount` field) and it broke mappings. This PR fixes it and adds few check in order to find incorrect action.
> [generic journey] fix mappings

- src/test/scala/org/kibanaLoadTest/helpers/KbnClient.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/CanvasJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/DashboardJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/DiscoverJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/LensJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/generic/GenericJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/generic/mapping/Journey.scala
- src/test/scala/org/kibanaLoadTest/simulation/generic/mapping/Request.scala
- src/test/scala/org/kibanaLoadTest/simulation/generic/mapping/ScalabilitySetup.scala
- src/test/scala/org/kibanaLoadTest/simulation/generic/mapping/Step.scala
- src/test/scala/org/kibanaLoadTest/test/KibanaAPITest.scala
Closes #325
This PR adds capability to run journey without making login call but setting Cookie header. GenericJourney will now check if "/internal/security/login" is listed in json file. If so, the journey will be run as before. If not, cookies will be generated based on max number of concurrent users and individually passed to each virtual user session.
This PR also updates some of existing journeys to skip login API request and start directly with main flow (**LensJourney, CanvasJourney, DashboardJourney and DiscoverJourney**)
> [Journeys] use cookie header instead of auth API call

- src/test/scala/org/kibanaLoadTest/helpers/HttpHelper.scala
Adds "br" to the `Accept-encoding` header. This will cause performance tests to use brotli compression if Kibana supports it.
> Accept brotli encoding

- src/test/scala/org/kibanaLoadTest/helpers/KbnClient.scala
- src/test/scala/org/kibanaLoadTest/simulation/BaseSimulation.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/CanvasJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/DashboardJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/DemoJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/DiscoverJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/LensJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/LongRunJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/TSVBGaugeJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/TSVBTimeSeriesJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/branch/TelemetryAPIJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/generic/GenericJourney.scala
According to Kibana security folks, it does not make any difference to use unique cookie for individual user (tcp connection), unless we test Kibana. Since I saw instability during running 100+ concurrent session creating, this PR limits it to 1 per scalability journey run.
I also updated other existing journeys to use generated session cookie instead of login api call.
> use 1 session

- src/test/scala/org/kibanaLoadTest/simulation/generic/core/JourneyBuilder.scala
- src/test/scala/org/kibanaLoadTest/simulation/generic/mapping/RequestStream.scala
There is not need to define stream start/endTime for single apis testing, this PR makes them optional.
> make startTime/endTime optional for stream

- src/test/scala/org/kibanaLoadTest/simulation/generic/core/ApiCall.scala
- src/test/scala/org/kibanaLoadTest/simulation/generic/core/JourneyBuilder.scala
- src/test/scala/org/kibanaLoadTest/simulation/generic/mapping/Step.scala
I recent spotted [this](https://gatling.io/docs/gatling/reference/current/core/injection/#meta-dsl) example of scalability testing in Gatling docs and think it can be a good approach for our single apis testing 
> [GenericJourney] support incrementUsersPerSec for scalability testing

- src/test/scala/org/kibanaLoadTest/KibanaConfiguration.scala
@wayneseymour was trying to run against cloud deployment on Azure and it fails since url has no `cloud` string in it. Using `providerName` should be more reliable.
> cloud check: use providerName

- src/test/resources/test/single_api_journey.json
- src/test/scala/org/kibanaLoadTest/simulation/generic/GenericJourney.scala
- src/test/scala/org/kibanaLoadTest/simulation/generic/mapping/Journey.scala
- src/test/scala/org/kibanaLoadTest/simulation/generic/mapping/Request.scala
- src/test/scala/org/kibanaLoadTest/test/JourneyTest.scala
This PR updates Journey mappings to support single api journey json format. 
Test with json loading example is added too.
> support single api capacity testing

- pom.xml
Reverts elastic/kibana-load-testing#354
```
| 2023-01-07 14:06:02 UTC  HEAD is now at 525074e Bump gatling.version from 3.8.4 to 3.9.0 (#354)
  | 2023-01-07 14:06:02 UTC | [ERROR] /var/lib/buildkite-agent/builds/kb-static-scalability-01/elastic/kibana-scalability-benchmarking/kibana/kibana-load-testing/src/test/scala/IDEPathHelper.scala:9: error: value ancestor is not a member of java.nio.file.Path
  | 2023-01-07 14:06:06 UTC | [ERROR]   val projectRootDir = gatlingConfUrl.ancestor(3)
  | 2023-01-07 14:06:06 UTC | [ERROR]                                       ^
  | 2023-01-07 14:06:06 UTC | [ERROR] 1 error
  | 2023-01-07 14:06:10 UTC | [ERROR] exception compilation error occurred!!!
  | 2023-01-07 14:06:10 UTC | org.apache.commons.exec.ExecuteException: Process exited with an error: 1 …
```
> Revert "Bump gatling.version from 3.8.4 to 3.9.0"

- README.md
- src/test/scala/org/kibanaLoadTest/simulation/generic/GenericJourney.scala
Since we restart Kibana & ES for each scalability journey, we can save time by skipping unloading data archives.
> [GenericJourney] add -DskipCleanupOnTeardown flag

- src/test/scala/org/kibanaLoadTest/helpers/ESArchiver.scala
- src/test/scala/org/kibanaLoadTest/helpers/ESClient.java
This PR copies logic from kibana es-archiver to retry on index creation failure: delete the existing index and create a new one.
> Es archiver/delete existing index

- catalog-info.yaml
The [Buildkite system](https://backstage.elastic.dev/catalog-graph?rootEntityRefs%5B%5D=system%3Adefault%2Fbuildkite&maxDepth=1&selectedKinds%5B%5D=api&selectedKinds%5B%5D=component&selectedKinds%5B%5D=domain&selectedKinds%5B%5D=group&selectedKinds%5B%5D=location&selectedKinds%5B%5D=system&selectedKinds%5B%5D=template&selectedKinds%5B%5D=user&unidirectional=true&mergeRelations=true&direction=LR&showFilters=true) in Backstage has a few components declared underneath it like this one that probably don't belong there. This is completely understandable because we're all new to Backstage, and it's easy to copy/paste fields like this. I'm proposing this change to help tidy that up. 😄
Summarize your PR.
> Remove association of component with Buildkite system

- .buildkite/pipeline.yml
Optimising pipeline to skip integration tests if step with unit tests failed
> [ci] make integration tests run only if unit tests pass
