elastic/kibana-load-testing

README.md, src/test/resources/config/cloud-7.10.0.conf, src/test/resources/config/cloud-7.9.2.conf, src/test/resources/config/deploy/7.9.3.conf, src/test/resources/config/local.conf, src/test/scala/org/kibanaLoadTest/KibanaConfiguration.scala, src/test/scala/org/kibanaLoadTest/helpers/Helper.scala
PR adds validation for config file, I also updated readme to include config examples and explain all 3 main cases (local, cloud, new deployment) in details.
I removed info about ingestion since it is not yet configured. Code is still in place.
=> add config validation, update readme

.ci/Jenkinsfile, pom.xml, src/test/scala/org/kibanaLoadTest/ESConfiguration.scala, src/test/scala/org/kibanaLoadTest/KibanaConfiguration.scala, src/test/scala/org/kibanaLoadTest/helpers/ESWrapper.scala, src/test/scala/org/kibanaLoadTest/helpers/Helper.scala, src/test/scala/org/kibanaLoadTest/helpers/LogParser.scala, src/test/scala/org/kibanaLoadTest/ingest/Main.scala, src/test/scala/org/kibanaLoadTest/simulation/BaseSimulation.scala, src/test/scala/org/kibanaLoadTest/test/IngestionTest.scala
- save deployment info to the file in `target/`
- run ingestion as a separate stage on CI
=> run report ingestion in post stage

.ci/Jenkinsfile, src/test/scala/org/kibanaLoadTest/simulation/BaseSimulation.scala, src/test/scala/org/kibanaLoadTest/simulation/CloudAtOnceJourney.scala, src/test/scala/org/kibanaLoadTest/simulation/CloudQuickJourney.scala
Part of #35
Scenario simulates the flow when all virtual start using Kibana at once
=> Add cloud scenario

src/test/scala/org/kibanaLoadTest/helpers/Helper.scala, src/test/scala/org/kibanaLoadTest/ingest/Main.scala
Since we can run multiple simulations, we need to ingest test results from multiple folders.
=> ingest multiple reports

src/test/scala/org/kibanaLoadTest/KibanaConfiguration.scala, src/test/scala/org/kibanaLoadTest/simulation/BaseSimulation.scala
Fix issue with locally build kibana
=> fix parsing build number

src/test/scala/org/kibanaLoadTest/KibanaConfiguration.scala, src/test/scala/org/kibanaLoadTest/helpers/ESWrapper.scala, src/test/scala/org/kibanaLoadTest/helpers/Helper.scala, src/test/scala/org/kibanaLoadTest/helpers/SimulationHelper.scala
Adding 2 new fields: 
`branch` - kibana-load-testing repo branch
`kibanaBranch` - kibana repo branch, empty for cloud testing
=> ingest branch names

src/test/scala/org/kibanaLoadTest/simulation/DemoJourney.scala, src/test/scala/org/kibanaLoadTest/simulation/local/AtOnceJourney.scala
=> update simulation  titles

.ci/Jenkinsfile_cloud
Hopefully it will improve CI run stability
=> [mvn] use retryHandler

.ci/Jenkinsfile, .ci/Jenkinsfile_cloud, scripts/deployAndTest.sh, scripts/deploy_on_cloud_and_run_test.sh, src/test/scala/org/kibanaLoadTest/scenario/Discover.scala, src/test/scala/org/kibanaLoadTest/simulation/DemoJourney.scala, src/test/scala/org/kibanaLoadTest/simulation/cloud/AtOnceJourney.scala, src/test/scala/org/kibanaLoadTest/simulation/local/AtOnceJourney.scala, src/test/scala/org/kibanaLoadTest/simulation/local/DiscoverAtOnce.scala
We agreed to run multiple simulations in order to better understand results and have a broad basis for future roadmap
=> [ci] run multiple simulations

.ci/Jenkinsfile, .ci/Jenkinsfile_cloud, .ci/loadPipeline.groovy, scripts/build_and_test.sh, scripts/deploy_and_test.sh, src/test/scala/org/kibanaLoadTest/helpers/CloudHttpClient.scala
Upload gatling html report + `simulation.log`, as well as `lastDeployment.txt`
https://kibana-ci.elastic.co/job/elastic+kibana+load-testing-cloud/123/
https://kibana-ci.elastic.co/job/elastic+kibana+load-testing/341/
=> [ci] upload artifacts

src/test/scala/org/kibanaLoadTest/helpers/HttpHelper.scala
Should help investigating login failures
=> log login request on failure

src/test/scala/org/kibanaLoadTest/simulation/BaseSimulation.scala
Wait 30 sec for data ingestion to be completed
=> wait 30 sec after loading data

src/test/scala/org/kibanaLoadTest/simulation/cloud/DiscoverAtOnce.scala
Adding discover-only scenario to compare with similar one for build run
=> add discover scenario for cloud run

.ci/Jenkinsfile, .ci/Jenkinsfile_cloud
=> [ci] Update pipelines

src/test/scala/org/kibanaLoadTest/deploy/DeleteAll.scala, src/test/scala/org/kibanaLoadTest/helpers/CloudHttpClient.scala
Deployments can have the same name and in this case the ones with the same names were not included. This PR fixes it.
Tested locally
=> find deployments with the same name

src/test/scala/org/kibanaLoadTest/scenario/Discover.scala
Small changes to improve discover scenario
=> [Discover] exit loop on failure & pause a second

.ci/Jenkinsfile
This PR adds more powerful worker for load testing on branch
=> [ci] xxl worker

puppeteer/src/helpers/compare.ts
This PR fixes some edge cases that were not covered during baseline check.
=> [puppeteer] fix compare requests logic

scripts/deploy_and_test.sh
Env is not installed (Node.js, yarn) and script is failing. This PR skips it for now. 
=> [ci] disable puppeteer script for cloud run

puppeteer/config.json
=> [puppeteer] fix kibana version

src/test/scala/org/kibanaLoadTest/helpers/Helper.scala, src/test/scala/org/kibanaLoadTest/helpers/ResponseParser.scala, src/test/scala/org/kibanaLoadTest/ingest/Main.scala, src/test/scala/org/kibanaLoadTest/test/IngestionTest.scala
Fixes parsing requests that failed on timeout and has no response information.
=> [ResponseParser] handle failed requests

src/test/resources/cloudPayload/createDeployment.json, src/test/resources/config/deploy/apm-default.conf, src/test/resources/config/deploy/apm-disable-instrumentation.conf, src/test/resources/config/deploy/apm-no-async.conf, src/test/resources/config/deploy/apm-no-metrics.conf, src/test/resources/config/deploy/apm-no-span-stacktrace.conf, src/test/resources/config/deploy/computeOptmized.conf, src/test/resources/config/deploy/custom.conf, src/test/resources/config/deploy/default.conf, src/test/resources/config/deploy/memoryOptimized.conf, src/test/scala/org/kibanaLoadTest/deploy/Create.scala, src/test/scala/org/kibanaLoadTest/helpers/CloudHttpClient.scala, src/test/scala/org/kibanaLoadTest/helpers/SimulationHelper.scala, src/test/scala/org/kibanaLoadTest/test/CloudAPITest.scala
Fixing issue with version list fetch from Elastic Cloud. Updating templating according GCP latest options.
=> [cloud] update deployment template, fix stack versions retrieve

.ci/Jenkinsfile_cloud, scripts/build_and_test.sh
Update cloud pipeline to use the same script for artefacts as branch one 
=> [ci] use the same artefacts upload script for cloud run

puppeteer/package.json, puppeteer/src/helpers/api.ts, puppeteer/yarn.lock
Bumping deps for puppeteer project
=> [puppeteer] update deps

scripts/deploy_and_test.sh, src/test/scala/org/kibanaLoadTest/simulation/cloud/AtOnceJourney.scala, src/test/scala/org/kibanaLoadTest/simulation/cloud/DemoJourney.scala, src/test/scala/org/kibanaLoadTest/simulation/cloud/DiscoverAtOnce.scala
Increasing number of users to make stats diff more noticeable
=> Bump cloud users

README.md, src/test/resources/config/cloud-7.10.0.conf, src/test/resources/config/cloud-7.11.0-snapshot.conf, src/test/resources/config/cloud-7.9.2.conf, src/test/resources/config/local.conf, src/test/resources/test/lastRun.txt, src/test/scala/org/kibanaLoadTest/KibanaConfiguration.scala, src/test/scala/org/kibanaLoadTest/deploy/Create.scala, src/test/scala/org/kibanaLoadTest/helpers/CloudHttpClient.scala, src/test/scala/org/kibanaLoadTest/helpers/HttpHelper.scala, src/test/scala/org/kibanaLoadTest/helpers/SimulationHelper.scala, src/test/scala/org/kibanaLoadTest/test/CloudAPITest.scala, src/test/scala/org/kibanaLoadTest/test/HelpersTest.scala
This PR gets ES snapshot metadata (version, buildHash, etc) via API call to ES instance and ingest to Kibana stats.
=> [ingest] fetch ES instance data and ingest

puppeteer/simulations.json, puppeteer/src/index.ts
Part of elastic/kibana/pull/119778
This PR requires to pass Gatling simulation class (e.g. `branch>lensJourney`) to run related puppeteer scenario. If scenario is not assigned to simulation, script will just exit.
=> [puppeteer] update cli to require simulation

src/test/scala/org/kibanaLoadTest/simulation/branch/LongRunJourney.scala
New simulation to see Kibana on long run
=> [branch] add LongRunJourney

src/test/scala/org/kibanaLoadTest/simulation/branch/DashboardJourney.scala, src/test/scala/org/kibanaLoadTest/simulation/branch/DiscoverJourney.scala, src/test/scala/org/kibanaLoadTest/simulation/branch/LensJourney.scala, src/test/scala/org/kibanaLoadTest/simulation/branch/TSVBGaugeJourney.scala, src/test/scala/org/kibanaLoadTest/simulation/branch/TSVBTimeSeriesJourney.scala
Put the load down to keep 99 pct within 30 sec threshold
=> [branch] set users down to 1200

src/test/scala/org/kibanaLoadTest/simulation/branch/AtOnceJourney.scala, src/test/scala/org/kibanaLoadTest/simulation/branch/CanvasJourney.scala, src/test/scala/org/kibanaLoadTest/simulation/branch/DashboardJourney.scala, src/test/scala/org/kibanaLoadTest/simulation/branch/DemoJourney.scala, src/test/scala/org/kibanaLoadTest/simulation/branch/LensJourney.scala
Put load down to be below 30 sec threshold
=> Change max users for simulations

puppeteer/src/index.ts, puppeteer/src/scenario/demoJourney.ts
Adding logic to debug puppeteer-based project, updating demoJourney scenario
=> add debug logic, update scenario

.ci/Jenkinsfile, src/test/scala/org/kibanaLoadTest/ingest/Main.scala
Run ingestion even if main stage failed. It will help to report partial  results, even if some simulations failed
=> run ingestion when main stage failed

pom.xml, src/test/scala/org/kibanaLoadTest/helpers/HttpHelper.scala
=> update gatling version to 3.7.3

scripts/build_and_test.sh
Changes needed for running metricbeat on non-ephemeral workers:
- checking to see if it's already installed. If it is, we only do the starting metricbeat step.
-  saving the PID when it's started
- closing metricbeat at the end of the script
For review,  we need to make sure that I didn't break anything with pushd and popd.
=> Adapt metricbeat section for running on metal

.ci/Jenkinsfile
Switch to bare metal machine for benchmarking. Leaving only 3 simulations to run on schedule: Canvas, Discover & Lens
=> try metal worker

.ci/Jenkinsfile
Cleans workspace on finish to have clean machine for each job run
=> [ci] clean workspace

puppeteer/package.json, puppeteer/src/helpers/api.ts, puppeteer/src/index.ts, puppeteer/yarn.lock
Update dependencies for puppeteer-based project.
=> update puppeteer project deps

scripts/build_and_test.sh
Adding script to reset memory
Closes #227
=> Reset memory before each simulation run

scripts/build_and_test.sh
Do not run metricbeat while we try to get consistence results
=> disable metricbeat

.ci/Jenkinsfile
delete workspace for failed builds
=> delete workspace for failed builds

puppeteer/src/index.ts
Automatically reads Kibana version from package.json file, should solve a problem of bumping version for puppeteer scripts.
=> fetch version from Kibana package.json

puppeteer/simulations.json
Temporary skipping API calls validation until elastic/kibana/issues/132895 is fixed
=> skip lens calls check due to kibana/issues/132895

src/test/scala/org/kibanaLoadTest/KibanaConfiguration.scala, src/test/scala/org/kibanaLoadTest/helpers/Helper.scala, src/test/scala/org/kibanaLoadTest/helpers/HttpHelper.scala, src/test/scala/org/kibanaLoadTest/simulation/BaseSimulation.scala, src/test/scala/org/kibanaLoadTest/simulation/generic/GenericJourney.scala, src/test/scala/org/kibanaLoadTest/test/HelpersTest.scala, src/test/scala/org/kibanaLoadTest/test/KibanaAPITest.scala
This PR refactors KibanaConfiguration class in order to fetch kibana version directly via API call to the testing instance. 
=> Refactor configuration class

src/test/resources/gatling.conf, src/test/resources/logback.xml
In order to optimize logging on CI, I did few changes to logback.xml
=> Update simulation logging

src/test/scala/org/kibanaLoadTest/simulation/generic/core/JourneyBuilder.scala
Temporary ignore some apis in json file
=> Filter out kibana requests

src/test/scala/org/kibanaLoadTest/KibanaConfiguration.scala
Quick fix for Cloud testing to unblock project usage.
=> don't make /api/status for cloud testing

src/test/scala/org/kibanaLoadTest/simulation/generic/core/ApiCall.scala
Allows to run capacity testing for bundles.
=> [GenericJourney] update buildNumber in bundle paths

README.md
Add the link Dima gave me for genning api keys.
=> Add the link Dima gave me for genning api keys.

pom.xml, src/test/scala/Engine.scala, src/test/scala/IDEPathHelper.scala, src/test/scala/Recorder.scala
=> Updating Gatling to 3.9.0

src/test/scala/org/kibanaLoadTest/helpers/KbnClient.scala
Fixing regular expression and error handling
=> fix getVersion

src/test/scala/org/kibanaLoadTest/helpers/KbnClient.scala, src/test/scala/org/kibanaLoadTest/test/KibanaClientTest.scala, src/test/scala/org/kibanaLoadTest/test/mocks/KibanaMockServer.scala
Adding more tests for kbnClient to test login failure handling.
=> add more tests for kbnClient

src/test/scala/org/kibanaLoadTest/simulation/generic/core/JourneyBuilder.scala
=> [JourneyBuilder] improve step parsing errors

src/main/resources/open_model/ess.discover.journey_15u.json, src/main/resources/open_model/ess.discover.journey_25u.json, src/main/resources/open_model/ess.discover.journey_27u.json, src/main/resources/open_model/ess.discover.journey_30u.json, src/main/resources/open_model/ess.discover.journey_50u.json, src/main/resources/open_model/serverless.discover.journey_20u.json, src/main/resources/open_model/serverless.discover.journey_30u.json, src/main/resources/open_model/serverless.discover.journey_35u.json, src/main/resources/open_model/serverless.discover.journey_50u.json, src/test/scala/org/kibanaLoadTest/helpers/KbnClient.scala, src/test/scala/org/kibanaLoadTest/simulation/generic/core/JourneyBuilder.scala
PR adds similar scenarios for both ess and serverless
=> Scenarios to test load on Serverless
